// Generated from the SkateQuest library (skills_v0.5.json) by
// scripts/skate-content.ts. Do not edit by hand — regenerate instead.
//
// This is reference content, not state: mechanics, drills and the mastery gate
// for each trick, written when the library was built and not expected to
// change. Progress lives in Notion; this does not.

export interface SkateContent {
  /** How the trick works. The cues. */
  mechanics: string[];
  /** What to actually do at the park to get it. */
  drills: string[];
  /** The criterion for calling it mastered. Judged by Jan, not by the app. */
  gate: string;
  terrain: string[];
  obstacles: string[];
  stances: string[];
  /** 1 to 10. Used to keep a stretch attempt from being reckless. */
  risk: number;
}

export const SKATE_CONTENT: Record<string, SkateContent> = {
  "foot_placement_reset": {
    mechanics: ["Front foot pivots after push.","Back foot returns without looking."],
    drills: ["10 front-foot pivots.","15 push-to-ride resets."],
    gate: "Can reset feet smoothly.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "heel_toe_press": {
    mechanics: ["Press through toes and heels.","Let ankles steer."],
    drills: ["3 x 1 min heel-toe.","10 slow lean turns."],
    gate: "Can control side-to-side pressure.",
    terrain: ["carpet","smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "safe_bail_reflex": {
    mechanics: ["Step forward and run it out.","Avoid leaning back."],
    drills: ["10 walking-speed step-offs.","5 fake wobbles into bail."],
    gate: "Can leave board calmly.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "stance_discovery": {
    mechanics: ["Find natural stance.","Front foot over bolts.","Knees soft."],
    drills: ["Step on/off 20x.","Stand 30s both ways."],
    gate: "Can stand centered and identify likely natural stance.",
    terrain: ["carpet","smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "static_balance": {
    mechanics: ["Feet over bolts.","Hips stacked.","Correct through ankles."],
    drills: ["1 min hold.","10 nose-tail shifts."],
    gate: "Can balance 1 minute.",
    terrain: ["carpet","grass","smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "foot_brake": {
    mechanics: ["Weight on front foot first.","Drag back foot lightly."],
    drills: ["10 gentle slowdowns.","Stop inside target zone."],
    gate: "Can slow down predictably.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 2,
  },
  "one_push_glide": {
    mechanics: ["Push with back foot only.","Front foot stable."],
    drills: ["10 single pushes.","Glide 5m."],
    gate: "Can push once, reset, and roll straight.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "repeated_pushing": {
    mechanics: ["Push back, not sideways.","Recover stance."],
    drills: ["3 pushes then coast x10.","Push 20m."],
    gate: "Can push repeatedly.",
    terrain: ["smooth flat","rough flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "roll_over_lines_and_cracks": {
    mechanics: ["Bend knees before crack.","Unweight slightly."],
    drills: ["Roll over painted line 20x.","Roll over small crack 10x."],
    gate: "Can roll over small surface changes.",
    terrain: ["smooth flat","rough flat"],
    obstacles: ["painted line","small crack"],
    stances: ["regular","goofy"],
    risk: 2,
  },
  "straight_roll_20m": {
    mechanics: ["Eyes ahead.","Soft knees."],
    drills: ["Roll 10m, 20m, 30m."],
    gate: "Can roll 20m.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "tail_stop": {
    mechanics: ["Back foot presses the tail just enough to lift the front wheels.","Front foot stays light and ready to step or reset.","Knees stay bent so the board does not shoot forward."],
    drills: ["Rock into tail stop and back to four wheels 20x.","Hold tail stop for 5 seconds.","Tail stop → four wheels → tail stop without looking down."],
    gate: "Can enter tail stop, hold 5 seconds, and return to four wheels calmly.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 2,
  },
  "backside_kickturn": {
    mechanics: ["Compress before nose lift.","Turn shoulders backside."],
    drills: ["10 x 45°.","5 x 90°."],
    gate: "Can kickturn backside 90°.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 2,
  },
  "carve_turns": {
    mechanics: ["Look into curve.","Lean through ankles and knees."],
    drills: ["5 toe-side carves.","5 heel-side carves."],
    gate: "Can turn both directions.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "fakie_roll_comfort": {
    mechanics: ["Look over shoulder.","Stay low."],
    drills: ["Roll fakie 5m x10.","Fakie carve."],
    gate: "Can roll fakie 10m.",
    terrain: ["smooth flat","bank"],
    obstacles: [],
    stances: ["fakie"],
    risk: 2,
  },
  "frontside_kickturn": {
    mechanics: ["Open front shoulder.","Return weight to both feet."],
    drills: ["10 x 45°.","5 x 90°."],
    gate: "Can kickturn frontside 90°.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 2,
  },
  "mini_slalom": {
    mechanics: ["Look one marker ahead.","Smooth pressure."],
    drills: ["Slalom 5 cones."],
    gate: "Can pass 5 markers.",
    terrain: ["smooth flat"],
    obstacles: ["cones"],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "pancake_flip": {
    mechanics: ["Keep the board close.","Jump lightly and let the board flip flat.","Land over the board, not behind it."],
    drills: ["Board-only pancake flip 20x.","One-foot catch drills.","Full pancake flip on carpet or smooth flat."],
    gate: "Can flip the board and step/land safely without panic.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 3,
  },
  "speed_check_carve": {
    mechanics: ["Use carve to reduce speed.","Keep knees soft."],
    drills: ["Carve to slow 10x."],
    gate: "Can reduce speed with carve.",
    terrain: ["smooth flat","rough flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 2,
  },
  "switch_push_intro": {
    mechanics: ["Treat it like day one.","Small pushes."],
    drills: ["10 tiny switch pushes.","Switch glide 3m."],
    gate: "Can push switch once.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["switch"],
    risk: 2,
  },
  "tail_stop_shuffle": {
    mechanics: ["Draw the front foot close to the tail before hopping.","Switch feet while the board remains in tail-stop position.","Use bent knees to absorb the hop."],
    drills: ["Tail stop hold 5 seconds.","Hop-switch feet 10x without exiting.","Tail stop shuffle → four wheels exit 5x."],
    gate: "Can hop-switch feet twice and exit to four wheels.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 3,
  },
  "tic_tac": {
    mechanics: ["Lighten nose.","Shoulders start rhythm."],
    drills: ["10 stationary tic-tacs.","Move forward 5m."],
    gate: "Can tic-tac forward.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","goofy"],
    risk: 1,
  },
  "body_varial": {
    mechanics: ["Board stays straight.","Body rotates."],
    drills: ["Stationary 180.","Rolling slow 180."],
    gate: "Can body varial and land.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","fakie","switch"],
    risk: 2,
  },
  "caveman": {
    mechanics: ["Drop board flat.","Jump to bolts."],
    drills: ["Board drop ankle height."],
    gate: "Can caveman and roll away.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch"],
    risk: 3,
  },
  "heelside_railstand": {
    mechanics: ["Board balances on its side edge.","Feet stay on wheels/opposite edge.","Exit safely before adding flips."],
    drills: ["Step into railstand with support.","Hold 5 seconds.","Railstand → wheels exit 10x."],
    gate: "Can enter, hold, and exit heelside railstand safely.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 4,
  },
  "hippie_jump": {
    mechanics: ["Jump up, not forward.","Land over bolts."],
    drills: ["5 stationary.","10 rolling over line."],
    gate: "Can jump and land rolling.",
    terrain: ["smooth flat"],
    obstacles: ["painted line","low bar"],
    stances: ["regular","fakie","switch"],
    risk: 2,
  },
  "manual": {
    mechanics: ["Hips adjust.","Nose low."],
    drills: ["Manual one board length.","10 distance attempts."],
    gate: "Can manual one board length.",
    terrain: ["smooth flat"],
    obstacles: ["manual pad"],
    stances: ["regular","switch"],
    risk: 3,
  },
  "manual_weight_shift": {
    mechanics: ["Hips move back.","Front wheels get light."],
    drills: ["10 front-wheel lifts.","10 rolling weight shifts."],
    gate: "Can lighten front wheels.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch"],
    risk: 2,
  },
  "monster_walk": {
    mechanics: ["Each step starts with arms and shoulders.","Press the leading end of the board and pivot 180° over the leading wheels.","Pause between steps before speeding up."],
    drills: ["Penguin walk: tiny alternating pivots.","One monster-walk step → pause → reset.","3 consecutive monster-walk steps."],
    gate: "Can do 3 controlled alternating 180° steps without rushing.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 3,
  },
  "ollie_phases": {
    mechanics: ["Setup, unweight, ankle snap, level, absorb."],
    drills: ["10 off-board jumps.","10 tail taps."],
    gate: "Can rehearse ollie phases.",
    terrain: ["carpet","smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 2,
  },
  "ride_up_a_bank": {
    mechanics: ["Approach straight and low."],
    drills: ["Ride halfway up/back."],
    gate: "Can ride up/down mellow bank.",
    terrain: ["bank"],
    obstacles: ["mellow bank"],
    stances: ["regular"],
    risk: 3,
  },
  "roll_off_tiny_curb": {
    mechanics: ["Approach straight.","Weight centered."],
    drills: ["Roll off 2-5cm edge 10x."],
    gate: "Can roll off tiny drop.",
    terrain: ["curb"],
    obstacles: ["tiny curb"],
    stances: ["regular"],
    risk: 3,
  },
  "switch_roll_10m": {
    mechanics: ["Eyes ahead.","Small pushes."],
    drills: ["Switch roll 5m x5.","Switch roll 10m x3."],
    gate: "Can roll switch 10m.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["switch"],
    risk: 3,
  },
  "tail_pop_control": {
    mechanics: ["Ankle snap, not stomp.","Jump upward."],
    drills: ["20 tail pops.","10 pop-and-step-off."],
    gate: "Can pop tail without jumping back.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 2,
  },
  "bank_kickturn": {
    mechanics: ["Turn at slowest point."],
    drills: ["BS/FS kickturn low on bank."],
    gate: "Can kickturn on bank both ways.",
    terrain: ["bank"],
    obstacles: ["mellow bank"],
    stances: ["regular"],
    risk: 4,
  },
  "curb_ride_off": {
    mechanics: ["Commit forward.","Absorb impact."],
    drills: ["Ride off curb 10x."],
    gate: "Can ride off curb.",
    terrain: ["curb"],
    obstacles: ["curb"],
    stances: ["regular"],
    risk: 4,
  },
  "endover": {
    mechanics: ["Alternating nose/tail pivots."],
    drills: ["Link 4 endovers."],
    gate: "Can link endovers.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch"],
    risk: 3,
  },
  "hand_flip_and_finger_flip": {
    mechanics: ["Grab or finger-flick the board while unweighting.","Jump enough for the board to rotate.","Land centered."],
    drills: ["Static hand flip.","Tail-stop finger flip.","Finger flip to step-off.","Finger flip to ride-away."],
    gate: "Can flip the board by hand/fingers and land wheels-down.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 4,
  },
  "nose_manual": {
    mechanics: ["Stay over front truck.","Back wheels low."],
    drills: ["10 nose shifts.","10 nose manual attempts."],
    gate: "Can nose manual half board length.",
    terrain: ["smooth flat"],
    obstacles: ["manual pad"],
    stances: ["regular","nollie"],
    risk: 4,
  },
  "powerslide": {
    mechanics: ["Unweight the board, push tail out 90 degrees.","Weight over front foot, knees bent, arms low.","Let wheels drift, then rotate back and roll on."],
    drills: ["Slide on wet/smooth patch at walking speed.","Grass powerslides for the motion.","90-degree slides both directions, add speed gradually."],
    gate: "Can scrub real speed with a controlled slide both frontside and backside.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 4,
  },
  "pump_transition": {
    mechanics: ["Compress into transition, extend up."],
    drills: ["Pump bank 10x.","5 cycles."],
    gate: "Can gain/maintain speed by pumping.",
    terrain: ["bank","quarter pipe"],
    obstacles: ["mellow transition"],
    stances: ["regular","fakie"],
    risk: 4,
  },
  "roll_to_fakie_on_bank": {
    mechanics: ["Ride up, slow, roll back fakie."],
    drills: ["Roll halfway up/back fakie 10x."],
    gate: "Can roll to fakie on bank.",
    terrain: ["bank"],
    obstacles: ["mellow bank"],
    stances: ["regular","fakie"],
    risk: 4,
  },
  "rolling_ollie": {
    mechanics: ["Same motion while moving.","Shoulders parallel."],
    drills: ["10 slow attempts.","Ollie over painted line."],
    gate: "Can land 3/10 rolling ollies.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["regular"],
    risk: 4,
  },
  "shuvit_rolling": {
    mechanics: ["Smaller scoop while rolling."],
    drills: ["10 slow attempts.","20 counted attempts."],
    gate: "Can land 3/10 rolling shuvits.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 4,
  },
  "shuvit_stationary": {
    mechanics: ["Back foot scoops.","Front foot guides."],
    drills: ["10 board-only scoops.","25 full attempts."],
    gate: "Can land 5/10 stationary shuvits.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 3,
  },
  "slappy_curb_feel": {
    mechanics: ["Shallow angle approach.","Let impact lock."],
    drills: ["Ride parallel to curb.","Tap front truck."],
    gate: "Can approach curb safely.",
    terrain: ["curb"],
    obstacles: ["curb"],
    stances: ["regular"],
    risk: 4,
  },
  "stationary_ollie": {
    mechanics: ["Jump, pop, level, absorb."],
    drills: ["10 carpet ollies.","25 concrete attempts."],
    gate: "Can land 5/10 stationary ollies.",
    terrain: ["carpet","smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 3,
  },
  "toeside_railstand": {
    mechanics: ["Reverse the railstand orientation.","Keep knees soft.","Practice exit before tricks out."],
    drills: ["Supported toeside entry.","Hold 5 seconds.","Toeside railstand → wheels exit."],
    gate: "Can enter and exit toeside railstand safely.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 5,
  },
  "walk_the_dog": {
    mechanics: ["Front foot controls the board’s spin.","Back foot steps to the nose and brings it around.","Keep rhythm slow before trying speed."],
    drills: ["Stationary foot placement rehearsal.","One walk-the-dog step → reset.","Four linked steps."],
    gate: "Can link four walk-the-dog steps with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 4,
  },
  "backside_180": {
    mechanics: ["Commit blind.","Turn head and shoulders."],
    drills: ["10 BS pivots.","20 rolling attempts."],
    gate: "Can land 3/10 BS 180s.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["regular"],
    risk: 4,
  },
  "boardslide_prep": {
    mechanics: ["Turn board 90 over target."],
    drills: ["Ollie 90 onto chalk line."],
    gate: "Can control boardslide entry shape.",
    terrain: ["smooth flat","curb"],
    obstacles: ["painted line","low rail later"],
    stances: ["regular"],
    risk: 5,
  },
  "boneless": {
    mechanics: ["Step down, grab board, jump."],
    drills: ["Static grab-step.","Rolling slow boneless."],
    gate: "Can boneless and roll away.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 4,
  },
  "fakie_ollie": {
    mechanics: ["Fakie timing.","Stay centered."],
    drills: ["10 fakie ollie attempts."],
    gate: "Can land 3/10 fakie ollies.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 4,
  },
  "fakie_rolling_ollie": {
    mechanics: ["Rebuild rolling ollie mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie rolling ollie with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["fakie"],
    risk: 4,
  },
  "frontside_180": {
    mechanics: ["Shoulders lead.","Roll away fakie."],
    drills: ["10 low FS 180s.","20 rolling attempts."],
    gate: "Can land 3/10 FS 180s.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["regular"],
    risk: 4,
  },
  "g_turn_prep": {
    mechanics: ["Move weight over the nose.","Keep the back wheels light.","Let the board arc rather than forcing a pivot."],
    drills: ["Static nose pressure holds.","Rolling nose lift for half a second.","Nose wheelie with tiny carve."],
    gate: "Can lift back wheels briefly and arc the board without stepping off.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 5,
  },
  "hippie_jump_over": {
    mechanics: ["Roll at steady speed, board passes under the obstacle.","Jump straight up — zero forward or sideways push.","Spot the board, land bolts."],
    drills: ["Jump over a line on the ground first.","Raise object height slowly (broomstick on cones).","Eyes on landing, not the object."],
    gate: "Can clear a knee-high bar and land back on the rolling board 3x in a row.",
    terrain: ["smooth flat"],
    obstacles: ["square flat bar","hedge","low chain"],
    stances: ["regular"],
    risk: 4,
  },
  "manual_2_board_lengths": {
    mechanics: ["Tiny hip corrections."],
    drills: ["Mark two board lengths."],
    gate: "Can manual two board lengths.",
    terrain: ["smooth flat"],
    obstacles: ["manual pad"],
    stances: ["regular","switch"],
    risk: 3,
  },
  "ollie_over_a_line": {
    mechanics: ["Look past line.","Pop before line."],
    drills: ["10 over chalk line."],
    gate: "Can clear a line 5/10.",
    terrain: ["smooth flat"],
    obstacles: ["painted line","crack"],
    stances: ["regular"],
    risk: 4,
  },
  "ollie_over_a_stick": {
    mechanics: ["Use low soft obstacle.","Level board."],
    drills: ["Start with hose.","10 clean clears."],
    gate: "Can clear small soft obstacle.",
    terrain: ["smooth flat"],
    obstacles: ["hose","stick"],
    stances: ["regular"],
    risk: 5,
  },
  "ollie_over_crack": {
    mechanics: ["Apply ollie mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete ollie over crack with control.",
    terrain: ["rough flat"],
    obstacles: ["crack"],
    stances: ["regular"],
    risk: 4,
  },
  "pop_shuvit": {
    mechanics: ["Pop down and scoop.","Shoulders quiet."],
    drills: ["10 pop-scoops.","20 rolling attempts."],
    gate: "Can land 4/10 pop shuvits.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 4,
  },
  "quarter_kickturn": {
    mechanics: ["Turn below coping first."],
    drills: ["Low BS/FS kickturns."],
    gate: "Can kickturn on mellow quarter.",
    terrain: ["quarter pipe"],
    obstacles: ["mellow quarter"],
    stances: ["regular"],
    risk: 5,
  },
  "rail_flip": {
    mechanics: ["Jump enough to let board rotate.","Keep the board close.","Catch over bolts."],
    drills: ["Railstand hold.","Board-only rail flip.","Rail flip to safe step-off.","Rail flip to ride-away."],
    gate: "Can rail flip from railstand to wheels.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 6,
  },
  "railstand_heelside": {
    mechanics: ["Flip board onto side edge."],
    drills: ["Static railstand holds."],
    gate: "Can enter/exit railstand.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "rock_to_fakie_prep": {
    mechanics: ["Front wheels cross line, return fakie."],
    drills: ["Front wheels over chalk line."],
    gate: "Can rock over visual line and return fakie.",
    terrain: ["bank","quarter pipe"],
    obstacles: ["line below coping"],
    stances: ["regular","fakie"],
    risk: 5,
  },
  "rolling_finger_flip": {
    mechanics: ["Keep rolling speed low.","Grab/flick while jumping.","Return feet over bolts."],
    drills: ["Tail-stop finger flip warm-up.","Rolling hand placement drill.","Rolling finger flip attempts."],
    gate: "Can rolling finger flip and roll away.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 5,
  },
  "slappy_curb_grind": {
    mechanics: ["Angle in, lift slightly."],
    drills: ["Low curb ride-on attempts."],
    gate: "Can lock briefly into curb.",
    terrain: ["curb"],
    obstacles: ["curb"],
    stances: ["regular"],
    risk: 5,
  },
  "spacewalk_prep": {
    mechanics: ["Hold manual low.","Swing the nose/tail gently side to side.","Do not let the lifted wheels touch down between swings."],
    drills: ["Manual hold 1 board length.","Manual with one small swing.","Three controlled swings."],
    gate: "Can manual while swinging the lifted end three times.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 5,
  },
  "switchblade": {
    mechanics: ["Keep weight light.","Shift feet rhythmically without stomping.","Use shoulders to guide direction changes."],
    drills: ["Tail stop shuffle warm-up.","Switchblade one cycle.","Three switchblade cycles into four-wheel exit."],
    gate: "Can perform three switchblade cycles and exit cleanly.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 5,
  },
  "truck_stand_entry": {
    mechanics: ["Start from nose-stop or tail-stop.","Lift board upright with hand while stepping onto truck.","Practice the dismount separately."],
    drills: ["Stand on truck with board held at angle.","Drop-and-half-flip dismount drill.","Hand pass drill.","Step-up drill."],
    gate: "Can stand briefly on the truck and dismount safely.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 6,
  },
  "boneless_180": {
    mechanics: ["Boneless plus 180 rotation."],
    drills: ["Boneless warm-up.","180 body varial."],
    gate: "Can boneless 180.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "fakie_backside_180": {
    mechanics: ["Rebuild backside 180 mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie backside 180 with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["fakie"],
    risk: 4,
  },
  "fakie_frontside_180": {
    mechanics: ["Rebuild frontside 180 mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie frontside 180 with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["fakie"],
    risk: 4,
  },
  "fakie_pop_shuvit": {
    mechanics: ["Rebuild pop shuvit mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie pop shuvit with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 4,
  },
  "firecracker": {
    mechanics: ["Approach stairs straight, moderate speed.","Lift nose so tail taps each step down.","Stay centered, absorb each tap with knees."],
    drills: ["Single curb tail-tap first.","2-stair, then longer sets.","Keep shoulders level throughout."],
    gate: "Can ride down a 3+ stair firecracker without stepping off.",
    terrain: ["stairs"],
    obstacles: ["2 stair","3 stair"],
    stances: ["regular"],
    risk: 5,
  },
  "frontside_pop_shuvit": {
    mechanics: ["Scoop forward/frontside.","Stay above board."],
    drills: ["10 FS scoops.","20 attempts."],
    gate: "Can land 3/10 FS pop shuvits.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "fs_50_50_curb": {
    mechanics: ["Both trucks lock.","Weight centered."],
    drills: ["Static lock-on.","Slow rolling lock."],
    gate: "Can 50-50 a curb.",
    terrain: ["curb"],
    obstacles: ["curb","low ledge"],
    stances: ["regular"],
    risk: 6,
  },
  "g_turn": {
    mechanics: ["Enter with enough roll.","Front foot controls the nose balance.","Upper body guides the arc."],
    drills: ["Nose manual arc attempts.","Quarter G-turns.","Half G-turns into controlled exit."],
    gate: "Can complete a controlled curved nose-manual turn.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 6,
  },
  "half_cab": {
    mechanics: ["Fakie approach.","Pop and turn 180."],
    drills: ["Fakie roll to pivot.","10 attempts."],
    gate: "Can land half cab.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 4,
  },
  "heelflip_setup": {
    mechanics: ["Flick outward off heel edge."],
    drills: ["Heel-flick practice.","One-foot catches."],
    gate: "Can create clean heelflip rotation.",
    terrain: ["carpet","smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "kickflip_setup": {
    mechanics: ["Flick through toe pocket.","Jump before flick."],
    drills: ["Flick-only drills.","One-foot catches."],
    gate: "Can create clean flip rotation.",
    terrain: ["carpet","smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "no_comply_180": {
    mechanics: ["Step off front foot, back foot pops/scoops 180."],
    drills: ["Step-pop 180 drills."],
    gate: "Can no-comply 180.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "no_comply_shuvit": {
    mechanics: ["Front foot steps off ahead of the board.","Back foot scoops a 180 shuvit.","Hop back on with the front foot leading."],
    drills: ["Stationary: step off + scoop, catch with hands allowed.","Add the hop-on without the scoop (caveman timing).","Combine at a slow roll."],
    gate: "Can land rolling no-comply shuvits 3x in a row.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 4,
  },
  "nollie": {
    mechanics: ["Pop nose.","Back foot levels."],
    drills: ["10 nose pops.","10 nollie attempts."],
    gate: "Can land 3/10 nollies.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["nollie"],
    risk: 5,
  },
  "nollie_rolling_ollie": {
    mechanics: ["Rebuild rolling ollie mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie rolling ollie with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["nollie"],
    risk: 5,
  },
  "nose_hook_impossible": {
    mechanics: ["Hook/lift from the nose.","Let the board wrap vertically.","Stay close enough to catch."],
    drills: ["Nose hook lift drill.","Half wrap drill.","Full nose hook impossible attempts."],
    gate: "Can create a controlled vertical wrap and land or step out safely.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 7,
  },
  "oldschool_fingerflip": {
    mechanics: ["Hand initiates board flip."],
    drills: ["Static fingerflip drills."],
    gate: "Can fingerflip and roll away.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "ollie_down_curb": {
    mechanics: ["Pop before edge.","Absorb drop."],
    drills: ["Ollie off tiny curb.","Ollie off normal curb."],
    gate: "Can ollie down curb.",
    terrain: ["curb"],
    obstacles: ["curb"],
    stances: ["regular"],
    risk: 5,
  },
  "ollie_over_cone": {
    mechanics: ["Apply ollie mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete ollie over cone with control.",
    terrain: ["smooth flat"],
    obstacles: ["small cone"],
    stances: ["regular"],
    risk: 6,
  },
  "ollie_up_curb": {
    mechanics: ["Pop before curb.","Lift knees."],
    drills: ["Ollie onto target.","Ollie up low curb."],
    gate: "Can ollie up curb 3/10.",
    terrain: ["curb"],
    obstacles: ["curb","low ledge"],
    stances: ["regular"],
    risk: 6,
  },
  "rail_walk": {
    mechanics: ["Small steps only.","Keep board edge stable.","Prioritize controlled exit."],
    drills: ["Railstand hold.","One rail-walk step.","Three rail-walk steps into exit."],
    gate: "Can take three controlled rail-walk steps.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 6,
  },
  "rock_to_fakie": {
    mechanics: ["Lift front wheels over coping.","Shift weight back."],
    drills: ["Rock below coping.","5 fakie exits."],
    gate: "Can rock to fakie low transition.",
    terrain: ["quarter pipe","mini ramp"],
    obstacles: ["coping"],
    stances: ["regular","fakie"],
    risk: 6,
  },
  "rollo_rail_to_rail": {
    mechanics: ["Keep weight centered over the board edge.","Move slowly.","Exit whenever balance is lost."],
    drills: ["Railstand hold both sides.","Half rollo with support.","Rail-to-rail and exit."],
    gate: "Can transfer railstand side-to-side and exit cleanly.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 6,
  },
  "spacewalk": {
    mechanics: ["Enter manual.","Swing the lifted end side-to-side.","Wider swings look better but control comes first."],
    drills: ["Three small swings.","Five continuous swings.","Spacewalk into endover or walk-the-dog exit."],
    gate: "Can spacewalk five swings and exit cleanly.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 6,
  },
  "switch_ollie": {
    mechanics: ["Rebuild from scratch.","Tiny height first."],
    drills: ["10 switch tail pops.","10 switch ollies."],
    gate: "Can land 3/10 switch ollies.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["switch"],
    risk: 5,
  },
  "switch_rolling_ollie": {
    mechanics: ["Rebuild rolling ollie mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch rolling ollie with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["switch"],
    risk: 5,
  },
  "truck_stand_5050": {
    mechanics: ["Do not pinch board between feet.","Stand on the truck, pass board hand-to-hand, then dismount.","Lift non-truck foot above the board before flipping down."],
    drills: ["Standing-on-truck drill.","Dismount drill.","Pass drill.","Step-up drill.","Full truck stand."],
    gate: "Can step into truck stand, pause, dismount and land wheels-down.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 7,
  },
  "360_shuvit": {
    mechanics: ["Strong 360 scoop.","Wait for rotation."],
    drills: ["Board-only 360 scoops.","20 attempts."],
    gate: "Can land 3/10 360 shuvits.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","fakie"],
    risk: 5,
  },
  "backside_boardslide": {
    mechanics: ["Land centered over rail/box."],
    drills: ["Low rail attempts."],
    gate: "Can boardslide low obstacle.",
    terrain: ["rail","ledge"],
    obstacles: ["flat bar","box"],
    stances: ["regular"],
    risk: 7,
  },
  "beanplant": {
    mechanics: ["Front foot plants on the deck/bank while front hand grabs the nose.","Board stays in the back hand-foot system; turn 180.","Stomp back in and ride down."],
    drills: ["Boneless on flat first (already required).","Static beanplant on a parked board.","Low bank before quarter."],
    gate: "Can beanplant on a bank or small quarter and ride away 3x.",
    terrain: ["bank","mini ramp"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "bigspin": {
    mechanics: ["Board 360, body 180."],
    drills: ["Shuvit + body varial drills."],
    gate: "Can land bigspin.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","fakie"],
    risk: 5,
  },
  "bs_50_50_curb": {
    mechanics: ["Blind-side approach."],
    drills: ["Backside lock-on practice."],
    gate: "Can backside 50-50 curb.",
    terrain: ["curb"],
    obstacles: ["curb","low ledge"],
    stances: ["regular"],
    risk: 7,
  },
  "carousel": {
    mechanics: ["Keep truck foot stable.","Hands guide the board around.","Rotate slowly before adding speed."],
    drills: ["Truck stand hold.","Quarter carousel.","Full carousel and dismount."],
    gate: "Can rotate through a carousel and dismount.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 7,
  },
  "casper": {
    mechanics: ["Upside-down board balance."],
    drills: ["Casper holds.","Flip out attempts."],
    gate: "Can enter/hold/exit casper.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 7,
  },
  "coconut_wheelie": {
    mechanics: ["Board stays on its side, not deck-dragging.","Balance over side wheels.","Exit safely."],
    drills: ["Static side-edge balance.","Tiny rolling coconut hold.","One board length coconut wheelie."],
    gate: "Can hold a short coconut wheelie.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 7,
  },
  "drop_in_small_quarter": {
    mechanics: ["Front foot stomps down.","Do not lean back."],
    drills: ["Bank practice.","Assisted first attempts."],
    gate: "Can drop in and roll away.",
    terrain: ["quarter pipe"],
    obstacles: ["mellow quarter"],
    stances: ["regular"],
    risk: 7,
  },
  "fakie_bebop": {
    mechanics: ["Use fakie momentum.","Coordinate feet with board flip/stance change.","Exit into a stable roll-away."],
    drills: ["Fakie roll warm-up.","Switchblade warm-up.","Low-speed fakie bebop attempts."],
    gate: "Can fakie bebop and roll away.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 7,
  },
  "frontside_180_down_curb": {
    mechanics: ["Apply frontside mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete frontside 180 down curb with control.",
    terrain: ["curb"],
    obstacles: ["curb"],
    stances: ["regular"],
    risk: 6,
  },
  "m_80": {
    mechanics: ["Kickflip-like entry.","Catch with foot on nose.","Pivot 180 before rear wheels settle."],
    drills: ["Kickflip catch drill.","Nose pivot drill.","M-80 sequence slow attempts."],
    gate: "Can complete flip-catch-pivot sequence and roll away.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 7,
  },
  "mini_ramp_line": {
    mechanics: ["Pump back and forth.","Kickturn below coping."],
    drills: ["5 wall-to-wall pumps."],
    gate: "Can keep mini-ramp line for 20s.",
    terrain: ["mini ramp"],
    obstacles: ["mini ramp"],
    stances: ["regular","fakie"],
    risk: 6,
  },
  "nollie_backside_180": {
    mechanics: ["Rebuild backside 180 mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie backside 180 with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["nollie"],
    risk: 5,
  },
  "nollie_frontside_180": {
    mechanics: ["Rebuild frontside 180 mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie frontside 180 with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["nollie"],
    risk: 5,
  },
  "nollie_pop_shuvit": {
    mechanics: ["Rebuild pop shuvit mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie pop shuvit with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["nollie"],
    risk: 5,
  },
  "ollie_to_manual": {
    mechanics: ["Pop onto pad and land in manual."],
    drills: ["Low manual pad attempts."],
    gate: "Can ollie to manual and roll off.",
    terrain: ["manual pad"],
    obstacles: ["manual pad","box"],
    stances: ["regular"],
    risk: 6,
  },
  "pogo_50_50_freestyle": {
    mechanics: ["Board vertical on tail truck."],
    drills: ["Static vertical holds."],
    gate: "Can hold pogo/50-50 position.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 7,
  },
  "railflip": {
    mechanics: ["Flip from railstand back to wheels."],
    drills: ["Board-only railflips."],
    gate: "Can railflip to wheels.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 7,
  },
  "rock_and_roll": {
    mechanics: ["Rock over coping then kickturn out."],
    drills: ["Rock to fakie warm-up."],
    gate: "Can rock and roll.",
    terrain: ["quarter pipe","mini ramp"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 7,
  },
  "rolling_fingerflip": {
    mechanics: ["Keep rolling speed."],
    drills: ["Slow rolling fingerflips."],
    gate: "Can rolling fingerflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 6,
  },
  "strawberry_milkshake": {
    mechanics: ["Press the board to primo as the front foot steps off (Steve Bentley's primo no-comply impossible).","Back foot flat on the ground scoops so the board wraps 360 around it.","When the board completes the wrap, hop both feet on and ride away."],
    drills: ["Rest position: comfortable primo stance.","Wrap-only reps on grass, catch with hands.","Add the front-foot hop last — no-comply 180 timing helps."],
    gate: "Wrap, catch and ride away clean 3x in a row.",
    terrain: ["smooth flat","carpet"],
    obstacles: [],
    stances: ["regular"],
    risk: 4,
  },
  "switch_backside_180": {
    mechanics: ["Rebuild backside 180 mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch backside 180 with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["switch"],
    risk: 5,
  },
  "switch_frontside_180": {
    mechanics: ["Rebuild frontside 180 mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch frontside 180 with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["switch"],
    risk: 5,
  },
  "switch_pop_shuvit": {
    mechanics: ["Rebuild pop shuvit mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch pop shuvit with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["switch"],
    risk: 5,
  },
  "backside_180_down_curb": {
    mechanics: ["Apply backside mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete backside 180 down curb with control.",
    terrain: ["curb"],
    obstacles: ["curb"],
    stances: ["regular"],
    risk: 7,
  },
  "bowl_carve_line": {
    mechanics: ["Use carve arcs.","Pump through pockets."],
    drills: ["3 connected carves."],
    gate: "Can link bowl carves.",
    terrain: ["bowl"],
    obstacles: ["shallow bowl"],
    stances: ["regular"],
    risk: 7,
  },
  "bs_axle_stall": {
    mechanics: ["Backside turn to coping."],
    drills: ["BS axle lock practice."],
    gate: "Can BS axle stall.",
    terrain: ["mini ramp"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 8,
  },
  "casper_flip": {
    mechanics: ["Flip from casper back to wheels."],
    drills: ["Casper warm-up."],
    gate: "Can casper flip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "fakie_bigspin": {
    mechanics: ["Rebuild bigspin mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie bigspin with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 5,
  },
  "frontside_boardslide": {
    mechanics: ["Frontside approach, center over rail."],
    drills: ["Low flat bar attempts."],
    gate: "Can frontside boardslide.",
    terrain: ["rail","ledge"],
    obstacles: ["flat bar","box"],
    stances: ["regular"],
    risk: 8,
  },
  "fs_axle_stall": {
    mechanics: ["Both trucks on coping."],
    drills: ["Deck-side lock-on practice."],
    gate: "Can FS axle stall.",
    terrain: ["mini ramp"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 8,
  },
  "full_cab": {
    mechanics: ["Fakie 360 rotation.","Spot landing early."],
    drills: ["Cab pivot drills.","Fakie 360 attempts."],
    gate: "Can land full cab.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 6,
  },
  "heelflip": {
    mechanics: ["Flick outward.","Catch over bolts."],
    drills: ["20 attempts.","Film foot path."],
    gate: "Can land 3/20 heelflips.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 6,
  },
  "kickflip": {
    mechanics: ["Pop, drag, flick, catch, absorb."],
    drills: ["10 flick catches.","20 attempts."],
    gate: "Can land 3/20 kickflips.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["regular"],
    risk: 6,
  },
  "ledge_50_50": {
    mechanics: ["Ollie onto both trucks."],
    drills: ["Low ledge ride-on.","Ollie-in attempts."],
    gate: "Can 50-50 low ledge.",
    terrain: ["ledge"],
    obstacles: ["low ledge","box"],
    stances: ["regular"],
    risk: 7,
  },
  "manual_shuvit_out": {
    mechanics: ["Stable manual before scoop out."],
    drills: ["Manual then shuv-out drills."],
    gate: "Can shuvit out of manual.",
    terrain: ["manual pad"],
    obstacles: ["manual pad"],
    stances: ["regular"],
    risk: 7,
  },
  "no_comply_360": {
    mechanics: ["Bigger scoop and body pivot."],
    drills: ["No-comply 180 warm-up."],
    gate: "Can no-comply 360.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 7,
  },
  "no_handed_pogo": {
    mechanics: ["Board squeezed/balanced without hand support.","Stay compact.","Exit before losing control."],
    drills: ["Supported pogo.","Hands-light pogo.","No-handed hold for 1 second."],
    gate: "Can hold no-handed pogo briefly and exit safely.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 9,
  },
  "nose_stall": {
    mechanics: ["Approach coping with speed to just reach it.","Lift tail, set the nose on the coping, weight over front truck.","Rock back in like a fakie tail stall entry."],
    drills: ["Nose pivots on a curb.","Tail stall to nose touch without committing.","Full stall, 1-second hold, back in."],
    gate: "Can nose stall and come back in cleanly 3x in a row.",
    terrain: ["mini ramp"],
    obstacles: [],
    stances: ["regular"],
    risk: 5,
  },
  "ollie_up_ledge": {
    mechanics: ["Apply ollie mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete ollie up ledge with control.",
    terrain: ["ledge"],
    obstacles: ["low ledge"],
    stances: ["regular"],
    risk: 7,
  },
  "stair_ollie": {
    mechanics: ["Speed and commitment.","Absorb impact."],
    drills: ["2-stair attempts."],
    gate: "Can ollie tiny stair set.",
    terrain: ["stairs"],
    obstacles: ["2 stair","3 stair"],
    stances: ["regular"],
    risk: 8,
  },
  "tail_stall": {
    mechanics: ["Tail locks on coping.","Re-enter with commitment."],
    drills: ["Tail tap warm-up."],
    gate: "Can tail stall and re-enter.",
    terrain: ["mini ramp"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 8,
  },
  "truck_stand_finger_flip": {
    mechanics: ["Hold truck stand first.","Finger flick initiates flip.","Hop and catch over grip tape."],
    drills: ["Fingerflip on ground.","Truck stand dismount.","Truck stand finger flip attempts."],
    gate: "Can fingerflip out of truck stand and land wheels-down.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 8,
  },
  "fakie_heelflip": {
    mechanics: ["Rebuild heelflip mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie heelflip with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 6,
  },
  "fakie_kickflip": {
    mechanics: ["Rebuild kickflip mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie kickflip with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["fakie"],
    risk: 6,
  },
  "feeble_stall": {
    mechanics: ["Back truck locks on coping, front truck dips over the far side.","Board points slightly down into the ramp.","Lift and turn back in off the back truck."],
    drills: ["Axle stall to front-truck dip.","Curb feeble position practice.","Commit the front foot lower each rep."],
    gate: "Locked feeble stall with controlled re-entry 3x.",
    terrain: ["mini ramp"],
    obstacles: [],
    stances: ["regular"],
    risk: 6,
  },
  "fs_disaster": {
    mechanics: ["FS 180 into disaster."],
    drills: ["Low transition attempts."],
    gate: "Can FS disaster and re-enter.",
    terrain: ["mini ramp"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 9,
  },
  "kickflip_manual": {
    mechanics: ["Catch kickflip in manual balance."],
    drills: ["Kickflip tail-heavy landings."],
    gate: "Can kickflip into manual.",
    terrain: ["manual pad"],
    obstacles: ["manual pad"],
    stances: ["regular"],
    risk: 8,
  },
  "kickflip_over_crack": {
    mechanics: ["Apply kickflip mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete kickflip over crack with control.",
    terrain: ["rough flat"],
    obstacles: ["crack"],
    stances: ["regular"],
    risk: 8,
  },
  "kickflip_over_line": {
    mechanics: ["Apply kickflip mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete kickflip over line with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["regular"],
    risk: 7,
  },
  "ledge_5_0": {
    mechanics: ["Back truck lock, nose lifted."],
    drills: ["5-0 curb warm-up."],
    gate: "Can 5-0 low ledge.",
    terrain: ["ledge"],
    obstacles: ["low ledge","box"],
    stances: ["regular"],
    risk: 8,
  },
  "nollie_bigspin": {
    mechanics: ["Rebuild bigspin mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie bigspin with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["nollie"],
    risk: 6,
  },
  "noseslide": {
    mechanics: ["Nose contacts obstacle.","Weight not too far forward."],
    drills: ["Static nose-on-ledge.","Short slides."],
    gate: "Can noseslide low ledge.",
    terrain: ["ledge"],
    obstacles: ["low ledge","box"],
    stances: ["regular"],
    risk: 8,
  },
  "ollie_gap": {
    mechanics: ["Apply ollie mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete ollie gap with control.",
    terrain: ["street"],
    obstacles: ["small gap"],
    stances: ["regular"],
    risk: 8,
  },
  "sidewinder": {
    mechanics: ["Transfer from one truck to the other.","Keep board vertical/upside-down through transfer.","Exit safely."],
    drills: ["Truck stand both sides.","Supported transfer.","Slow sidewinder attempts."],
    gate: "Can transfer truck-to-truck and dismount.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","switch later"],
    risk: 9,
  },
  "slash_grind": {
    mechanics: ["Carve into coping at angle."],
    drills: ["Carve below coping.","Tap coping."],
    gate: "Can slash grind and continue line.",
    terrain: ["bowl","quarter pipe"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 8,
  },
  "switch_bigspin": {
    mechanics: ["Rebuild bigspin mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch bigspin with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["switch"],
    risk: 6,
  },
  "varial_heelflip": {
    mechanics: ["FS shuv scoop plus heelflip flick."],
    drills: ["FS pop shuv warm-up.","Heelflip warm-up."],
    gate: "Can land varial heelflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 7,
  },
  "varial_kickflip": {
    mechanics: ["Backside shuv scoop plus kickflip flick."],
    drills: ["Pop shuv warm-up.","Kickflip warm-up."],
    gate: "Can land varial kickflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","fakie"],
    risk: 7,
  },
  "wallride": {
    mechanics: ["Approach at an angle, slight ollie up onto the wall.","All four wheels on the wall, weight pressing in.","Turn out and drop back to flat, absorb."],
    drills: ["Bank-to-wall setups first.","One-wheel then two-wheel wall touches.","Commit to a full wheelbase on the wall."],
    gate: "Can ride the wall and land back rolling 3x.",
    terrain: ["wall","bank"],
    obstacles: [],
    stances: ["regular"],
    risk: 6,
  },
  "backside_flip": {
    mechanics: ["Blind backside rotation plus kickflip."],
    drills: ["BS 180 warm-up.","Kickflip warm-up."],
    gate: "Can land backside flip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "bs_disaster": {
    mechanics: ["BS 180 into disaster."],
    drills: ["Low transition attempts."],
    gate: "Can BS disaster and re-enter.",
    terrain: ["mini ramp"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 10,
  },
  "carve_grind": {
    mechanics: ["Carve up to coping and grind through arc."],
    drills: ["Slash warm-up."],
    gate: "Can carve grind coping.",
    terrain: ["bowl"],
    obstacles: ["coping"],
    stances: ["regular"],
    risk: 9,
  },
  "double_kickflip": {
    mechanics: ["More height, faster flick."],
    drills: ["High ollie warm-up.","Double rotation attempts."],
    gate: "Can land double kickflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "frontside_flip": {
    mechanics: ["FS 180 plus kickflip."],
    drills: ["FS 180 warm-up.","Kickflip warm-up."],
    gate: "Can land frontside flip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "frontside_heelflip": {
    mechanics: ["FS 180 plus heelflip."],
    drills: ["FS 180 warm-up.","Heelflip warm-up."],
    gate: "Can land frontside heelflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "half_cab_flip": {
    mechanics: ["Fakie roll, wind up like a half cab.","Flick the kickflip mid-180.","Catch with shoulders finished, roll out regular."],
    drills: ["Half cabs with exaggerated flick foot position.","Fakie kickflips landing 90 turned.","Marry the two, commit the catch."],
    gate: "Can land half cab flips 3x in a session.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 6,
  },
  "hardflip": {
    mechanics: ["FS shuv plus kickflip.","Jump high."],
    drills: ["FS shuv warm-up.","Kickflip warm-up."],
    gate: "Can land hardflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "inward_heelflip": {
    mechanics: ["Backside shuv plus heelflip."],
    drills: ["Pop shuv warm-up.","Heelflip warm-up."],
    gate: "Can land inward heelflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "kickflip_up_curb": {
    mechanics: ["Apply kickflip mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete kickflip up curb with control.",
    terrain: ["curb"],
    obstacles: ["curb"],
    stances: ["regular"],
    risk: 9,
  },
  "nollie_heelflip": {
    mechanics: ["Rebuild heelflip mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie heelflip with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["nollie"],
    risk: 7,
  },
  "nollie_kickflip": {
    mechanics: ["Rebuild kickflip mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie kickflip with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["nollie"],
    risk: 7,
  },
  "nosegrind": {
    mechanics: ["Ollie into front-truck-only lock on the ledge.","Weight stacked over the nose, back truck floating.","Slight pop or let it run off the end."],
    drills: ["Nose manual pads first.","5-0 to nose-shift on a curb.","Short nosegrinds, grow the distance."],
    gate: "Locked nosegrind the length of a board 3x.",
    terrain: ["ledge","curb"],
    obstacles: ["curb","low ledge"],
    stances: ["regular"],
    risk: 7,
  },
  "switch_heelflip": {
    mechanics: ["Rebuild heelflip mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch heelflip with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["switch"],
    risk: 7,
  },
  "switch_kickflip": {
    mechanics: ["Rebuild kickflip mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch kickflip with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["switch"],
    risk: 7,
  },
  "tre_flip": {
    mechanics: ["Back foot does most scoop.","Flick light."],
    drills: ["360 shuv warm-up.","Kickflip warm-up."],
    gate: "Can land tre flip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 8,
  },
  "bigflip": {
    mechanics: ["Bigspin body motion plus kickflip."],
    drills: ["Bigspin warm-up.","Kickflip warm-up."],
    gate: "Can land bigflip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular","fakie"],
    risk: 9,
  },
  "blunt_to_fakie": {
    mechanics: ["Tail/wheels lock above coping.","Pop back fakie."],
    drills: ["Tail stall warm-up."],
    gate: "Can blunt to fakie.",
    terrain: ["mini ramp"],
    obstacles: ["coping"],
    stances: ["regular","fakie"],
    risk: 10,
  },
  "crooked_grind": {
    mechanics: ["Front truck pinches at angle."],
    drills: ["Static crook lock.","Short grinds."],
    gate: "Can crooked grind.",
    terrain: ["ledge"],
    obstacles: ["low ledge","ledge"],
    stances: ["regular"],
    risk: 9,
  },
  "fakie_tre_flip": {
    mechanics: ["Rebuild tre flip mechanics in fakie.","Keep speed low first."],
    drills: ["Warm up fakie rolling.","Try tiny versions first."],
    gate: "Can land fakie tre flip with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["fakie"],
    risk: 8,
  },
  "feeble_grind": {
    mechanics: ["Back truck grinds, front truck hangs over the far side.","Nose points slightly down and across.","Straighten out to exit."],
    drills: ["Feeble stall on curb (or quarter).","Boardslide-to-feeble shift on a low bar.","Commit front foot over, not on top."],
    gate: "Locked feeble the length of a board with rideaway 3x.",
    terrain: ["rail","ledge"],
    obstacles: ["square flat bar","low ledge"],
    stances: ["regular"],
    risk: 7,
  },
  "kickflip_down_small_set": {
    mechanics: ["Same kickflip, more impact."],
    drills: ["Flat kickflip warm-up.","Ollie set warm-up."],
    gate: "Can kickflip small set.",
    terrain: ["stairs"],
    obstacles: ["2 stair","3 stair"],
    stances: ["regular"],
    risk: 10,
  },
  "laser_flip": {
    mechanics: ["360 FS shuv plus heelflip."],
    drills: ["FS 360 shuv drills.","Heelflip warm-up."],
    gate: "Can land laser flip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 9,
  },
  "lipslide": {
    mechanics: ["Ollie over rail into slide."],
    drills: ["Low flat bar only."],
    gate: "Can lipslide low rail.",
    terrain: ["rail"],
    obstacles: ["flat bar","round rail"],
    stances: ["regular"],
    risk: 10,
  },
  "nose_manual_nollie_flip_out": {
    mechanics: ["Hold nose manual, nollie flip out."],
    drills: ["Nose manual warm-up.","Nollie flip warm-up."],
    gate: "Can nollie flip out of nose manual.",
    terrain: ["manual pad"],
    obstacles: ["manual pad"],
    stances: ["nollie"],
    risk: 10,
  },
  "smith_grind": {
    mechanics: ["Back truck grinds, front truck dips down the near side.","Front foot pushes the nose down and forward.","Pop or lift out to flat."],
    drills: ["5-0 with progressive nose dip.","Curb smith stalls.","Low square rail before ledges."],
    gate: "Locked smith grind with clean exit 3x.",
    terrain: ["ledge","rail"],
    obstacles: ["low ledge","square flat bar"],
    stances: ["regular"],
    risk: 7,
  },
  "tailslide": {
    mechanics: ["Tail contacts after 90 turn."],
    drills: ["Tail-on-ledge position."],
    gate: "Can tailslide low ledge.",
    terrain: ["ledge"],
    obstacles: ["low ledge","ledge"],
    stances: ["regular"],
    risk: 10,
  },
  "tre_flip_over_line": {
    mechanics: ["Apply tre mechanics in this terrain context.","Scale only when flat version is reliable."],
    drills: ["Warm up flat version.","Use smallest safe obstacle."],
    gate: "Can complete tre flip over line with control.",
    terrain: ["smooth flat"],
    obstacles: ["painted line"],
    stances: ["regular"],
    risk: 9,
  },
  "bluntslide": {
    mechanics: ["Pop high enough to lock tail-and-back-wheels on top.","Slide with weight stacked over the tail.","Small pop-out to exit, shoulders lead."],
    drills: ["Blunt stalls on curb.","Tailslide higher lock each session.","Short bluntslides on waxed low ledge."],
    gate: "Locked bluntslide with pop-out rideaway 3x.",
    terrain: ["ledge","rail"],
    obstacles: ["low ledge","square flat bar"],
    stances: ["regular"],
    risk: 8,
  },
  "nightmare_flip": {
    mechanics: ["Varial plus double kickflip."],
    drills: ["Double kickflip warm-up.","Varial warm-up."],
    gate: "Can land nightmare flip.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["regular"],
    risk: 10,
  },
  "nollie_tre_flip": {
    mechanics: ["Rebuild tre flip mechanics in nollie.","Keep speed low first."],
    drills: ["Warm up nollie rolling.","Try tiny versions first."],
    gate: "Can land nollie tre flip with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["nollie"],
    risk: 9,
  },
  "switch_tre_flip": {
    mechanics: ["Rebuild tre flip mechanics in switch.","Keep speed low first."],
    drills: ["Warm up switch rolling.","Try tiny versions first."],
    gate: "Can land switch tre flip with control.",
    terrain: ["smooth flat"],
    obstacles: [],
    stances: ["switch"],
    risk: 9,
  },
};

export function skateContent(skillId: string): SkateContent | null {
  return SKATE_CONTENT[skillId] ?? null;
}
